ATS-863: Update to latest Java Base Image on CentOS 8 (& Open JDK 11.0.10)
Alfresco/alfresco-transform-core pull request #333
Opened 2021-02-12 08:48 UTC by montgolfiere

- to resolve 2 medium (at time of writing) in quay.io
- update to CentOS 7 to 8 (aligned with Repo decision)

2021-02-12 09:28 UTC, TheOutsSeeker requested changes
Did you run the build and test locally first? There seems to be some build error which might be related to CentOS8 bump.

2021-02-12 12:24 UTC, KikoUK approved these changes

2021-02-15 15:46 UTC, montgolfiere commented
@TheOutsSeeker Fixed by upgrading ImageMagick 7.0.7-11 to 7.0.7-59 (see also ACS-1174).

2021-02-15 15:48 UTC, TheOutsSeeker approved these changes

2021-02-15 15:49 UTC, merged