ATS-886 /  ATS-907: Automation tests: light-weight management of rich media files (IPTC metadata extract)
Alfresco/alfresco-transform-core pull request #395
Opened 2021-04-29 13:48 UTC by aymanthefirst

Added unit tests in alfresco-transform-tika\alfresco-transform-tika-boot\src\test\java\org\alfresco\transformer\TikaMetadataExtractsIT.java and their corresponding quick files, to test the IPTC metadata extractions as listed by file type in alfresco-transform-tika/alfresco-transform-tika/src/main/resources/tika_engine_config.json#L532-L548

2021-04-30 09:14 UTC, PunchedChimera requested changes
A lot of files have been modified that shouldn't have. Please revert.

2021-04-30 09:14 UTC, PunchedChimera commented on alfresco-transform-tika/alfresco-transform-tika-boot/src/test/java/org/alfresco/transformer/TikaMetadataExtractsIT.java
> +import static org.alfresco.transformer.util.MimetypeMap.*;
Please revert and add specific variables that are being imported.

2021-04-30 09:14 UTC, PunchedChimera commented on alfresco-transform-tika/alfresco-transform-tika-boot/src/test/resources/quick.m4a_metadata.json
> +  "{http://www.alfresco.org/model/audio/1.0}artist" : "Hauskaz",
Please revert this file. m4a is not handled by IPTC extraction so should not change.

2021-04-30 09:14 UTC, PunchedChimera commented on alfresco-transform-tika/alfresco-transform-tika-boot/src/test/resources/quick.mp3_metadata.json
> +  "{http://www.alfresco.org/model/audio/1.0}artist" : "Hauskaz",
Please revert this file. mp3 is not handled by IPTC extraction so should not change.

2021-04-30 09:14 UTC, PunchedChimera commented on alfresco-transform-tika/alfresco-transform-tika-boot/src/test/resources/quick.odf_metadata.json
> +  "{http://www.alfresco.org/model/content/1.0}created" : 1138370122000,
Please revert this file. odf is not handled by IPTC extraction so should not change.

2021-04-30 09:14 UTC, PunchedChimera commented on alfresco-transform-tika/alfresco-transform-tika-boot/src/test/resources/quick.odg_metadata.json
> +  "{http://www.alfresco.org/model/content/1.0}created" : 1138369571000,
Please revert this file. odg is not handled by IPTC extraction so should not change.

2021-04-30 09:14 UTC, PunchedChimera commented on alfresco-transform-tika/alfresco-transform-tika-boot/src/test/resources/quick.ods_metadata.json
> +  "{http://www.alfresco.org/model/content/1.0}created" : 845343208000,
Please revert this file. ods is not handled by IPTC extraction so should not change.

2021-04-30 09:14 UTC, PunchedChimera commented on alfresco-transform-tika/alfresco-transform-tika-boot/src/test/resources/quick.odt_metadata.json
> +  "{http://www.alfresco.org/model/content/1.0}created" : 1126060440000,
Please revert this file. odt is not handled by IPTC extraction so should not change.

2021-04-30 09:14 UTC, PunchedChimera commented on alfresco-transform-tika/alfresco-transform-tika-boot/src/test/resources/quick.ogg_metadata.json
> +  "{http://www.alfresco.org/model/audio/1.0}artist" : "Hauskaz",
Please revert this file. ogg is not handled by IPTC extraction so should not change.

2021-04-30 09:14 UTC, PunchedChimera commented on alfresco-transform-tika/alfresco-transform-tika-boot/src/test/resources/quick.otg_metadata.json
> +  "{http://www.alfresco.org/model/content/1.0}created" : 1138369571000,
Please revert this file. otg is not handled by IPTC extraction so should not change.

2021-04-30 09:14 UTC, PunchedChimera commented on alfresco-transform-tika/alfresco-transform-tika-boot/src/test/resources/quick.otp_metadata.json
> +  "{http://www.alfresco.org/model/content/1.0}created" : 1179324646000,
Please revert this file. otp is not handled by IPTC extraction so should not change.

2021-04-30 09:14 UTC, PunchedChimera commented on alfresco-transform-tika/alfresco-transform-tika-boot/src/test/resources/quick.ots_metadata.json
> +  "{http://www.alfresco.org/model/content/1.0}created" : 845343208000,
Please revert this file. ots is not handled by IPTC extraction so should not change.

2021-04-30 09:14 UTC, PunchedChimera commented on alfresco-transform-tika/alfresco-transform-tika-boot/src/test/resources/quick.ott_metadata.json
> +  "{http://www.alfresco.org/model/content/1.0}created" : 1126060440000,
Please revert this file. ott is not handled by IPTC extraction so should not change.

2021-04-30 09:14 UTC, PunchedChimera commented on alfresco-transform-tika/alfresco-transform-tika-boot/src/test/resources/quick.sxw_metadata.json
> +  "{http://www.alfresco.org/model/content/1.0}created" : 1126060440000,
Please revert this file. sxw is not handled by IPTC extraction so should not change.

2021-04-30 09:14 UTC, PunchedChimera commented on alfresco-transformer-base/src/main/java/org/alfresco/transformer/util/MimetypeMap.java
> +    String MIMETYPE_IMAGE_RAW_webp = "image/webp";
Consistency
```suggestion
    String MIMETYPE_IMAGE_RAW_WEBP = "image/webp";
```

2021-04-30 11:24 UTC, PunchedChimera commented on alfresco-transform-tika/alfresco-transform-tika-boot/src/test/resources/quick.tiff_metadata.json
> -  "{http://purl.org/dc/elements/1.1/}title" : "The quick brown fox jumps over the lazy dog",
This doesn't look right? Why have you removed the ITPC metadata?

2021-05-05 08:17 UTC, aymanthefirst commented
This PR can now be closed because it has been broken down into two PRs, of which the [first](https://github.com/Alfresco/alfresco-transform-core/pull/398) is merged.

2021-05-05 08:17 UTC, closed without merging