ATS-913: Tech debt: add more T-Core Unit tests (part 2) for IPTC metadata extract
Alfresco/alfresco-transform-core pull request #414
Opened 2021-05-26 11:16 UTC by aymanthefirst

Added RAW tests and their corresponding files for IPTC metadata extraction

2021-05-27 08:40 UTC, montgolfiere requested changes
As per ATS-913, what about other existing quick image formats ?

eg. quickIPTC.png, quickIPTC.gif ... etc (maybe consistent with quickIPTC.jpg or similar)

For the RAW files, what is the source of the original files please ?

2021-05-27 09:46 UTC, aymanthefirst commented
@montgolfiere I just saw your last comment and change of description on https://alfresco.atlassian.net/browse/ATS-913

Now I understand the problem.

So I will make make a new PR with those changes. It shouldn't take long as the time-consuming part of building the project is done. 

What shall we do with this PR?

2021-06-02 10:24 UTC, KikoUK approved these changes

2021-06-02 13:47 UTC, PunchedChimera approved these changes

2021-06-02 14:00 UTC, merged